name: Run Vscanner

on:
  workflow_dispatch:     # Run manually and on push
  push:
      branches:
        - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t vscanner .

    - name: Run Scanner
      run: |
        docker run --rm \
        -v "${{ github.workspace }}:/output" \
        vscanner scanme.nmap.org

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: vscanner-report
        path: scan_report.txt
